# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackernews_id', models.IntegerField()),
                ('title', models.TextField(default=b'NA')),
                ('url', models.TextField()),
                ('user', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
